In [ ]:
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Evaluate Gemini and DocAI Custom Extractor with tabular information

{TODO: Update the links below. Use the next code cell to generate the HTML, then delete the code cell.}

<table align="left">
  <td style="text-align: center">
    <a href="https://colab.research.google.com/github/GoogleCloudPlatform/generative-ai/blob/main/notebook_template.ipynb">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo"><br> Open in Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/colab/import/https:%2F%2Fraw.githubusercontent.com%2FGoogleCloudPlatform%2Fgenerative-ai%2Fmain%2Fnotebook_template.ipynb">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo"><br> Open in Colab Enterprise
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://raw.githubusercontent.com/GoogleCloudPlatform/generative-ai/main/notebook_template.ipynb">
      <img src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo"><br> Open in Vertex AI Workbench
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://console.cloud.google.com/bigquery/import?url=https://github.com/GoogleCloudPlatform/generative-ai/blob/main/notebook_template.ipynb">
      <img src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery Studio logo"><br> Open in BigQuery Studio
    </a>
  </td>
  <td style="text-align: center">
    <a href="https://github.com/GoogleCloudPlatform/generative-ai/blob/main/notebook_template.ipynb">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo"><br> View on GitHub
    </a>
  </td>
</table>

<div style="clear: both;"></div>

<b>Share to:</b>

<a href="https://www.linkedin.com/sharing/share-offsite/?url=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/notebook_template.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="LinkedIn logo">
</a>

<a href="https://bsky.app/intent/compose?text=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/notebook_template.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="Bluesky logo">
</a>

<a href="https://twitter.com/intent/tweet?url=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/notebook_template.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X logo">
</a>

<a href="https://reddit.com/submit?url=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/notebook_template.ipynb" target="_blank">
  <img width="20px" src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit logo">
</a>

<a href="https://www.facebook.com/sharer/sharer.php?u=https%3A//github.com/GoogleCloudPlatform/generative-ai/blob/main/notebook_template.ipynb" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg" alt="Facebook logo">
</a>

In [ ]:
# TODO: REMOVE THIS CELL FROM YOUR NOTEBOOK ###

import re
from urllib.parse import quote

from IPython.display import Markdown, display


def generate_html(file_path: str):
    match = re.search(
        r"(?:https://)?(?:github\.com/)?(?:GoogleCloudPlatform/)?(?:generative-ai/)?(?:blob/)?(?:main/)?([\w/-]+.ipynb)",
        file_path,
    )
    if not match:
        return "Could not generate table."

    file_path = match.group(1)

    base_url = "https://github.com/GoogleCloudPlatform/generative-ai/blob/main/"
    raw_github_url = (
        "https://raw.githubusercontent.com/GoogleCloudPlatform/generative-ai/main/"
    )

    colab_url = "https://colab.research.google.com/github/GoogleCloudPlatform/generative-ai/blob/main/"
    colab_enterprise_url = f"https://console.cloud.google.com/vertex-ai/colab/import/{raw_github_url.replace('/', '%2F')}"
    vertex_ai_url = f"https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url={raw_github_url}"
    bigquery_studio_url = (
        f"https://console.cloud.google.com/bigquery/import?url={base_url}"
    )

    linkedin_url = "https://www.linkedin.com/sharing/share-offsite/?url="
    bluesky_url = "https://bsky.app/intent/compose?text="
    twitter_url = "https://twitter.com/intent/tweet?url="
    reddit_url = "https://reddit.com/submit?url="
    facebook_url = "https://www.facebook.com/sharer/sharer.php?u="

    encoded_url = quote(f"{base_url}{file_path}")

    html = f"""
```html
<table align="left">
  <td style="text-align: center">
    <a href="{colab_url}{file_path}">
      <img width="32px" src="https://www.gstatic.com/pantheon/images/bigquery/welcome_page/colab-logo.svg" alt="Google Colaboratory logo"><br> Open in Colab
    </a>
  </td>
  <td style="text-align: center">
    <a href="{colab_enterprise_url}{file_path.replace('/', '%2F')}">
      <img width="32px" src="https://lh3.googleusercontent.com/JmcxdQi-qOpctIvWKgPtrzZdJJK-J3sWE1RsfjZNwshCFgE_9fULcNpuXYTilIR2hjwN" alt="Google Cloud Colab Enterprise logo"><br> Open in Colab Enterprise
    </a>
  </td>
  <td style="text-align: center">
    <a href="{vertex_ai_url}{file_path}">
      <img src="https://www.gstatic.com/images/branding/gcpiconscolors/vertexai/v1/32px.svg" alt="Vertex AI logo"><br> Open in Vertex AI Workbench
    </a>
  </td>"""

    # Add BigQuery Studio link only if the flag is True
    if INCLUDE_BIGQUERY_STUDIO:
        html += f"""
  <td style="text-align: center">
    <a href="{bigquery_studio_url}{file_path}">
      <img src="https://www.gstatic.com/images/branding/gcpiconscolors/bigquery/v1/32px.svg" alt="BigQuery Studio logo"><br> Open in BigQuery Studio
    </a>
  </td>"""

    html += f"""
  <td style="text-align: center">
    <a href="{base_url}{file_path}">
      <img width="32px" src="https://www.svgrepo.com/download/217753/github.svg" alt="GitHub logo"><br> View on GitHub
    </a>
  </td>
</table>

<div style="clear: both;"></div>

<b>Share to:</b>

<a href="{linkedin_url}{encoded_url}" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/8/81/LinkedIn_icon.svg" alt="LinkedIn logo">
</a>

<a href="{bluesky_url}{encoded_url}" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Bluesky_Logo.svg" alt="Bluesky logo">
</a>

<a href="{twitter_url}{encoded_url}" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/5/5a/X_icon_2.svg" alt="X logo">
</a>

<a href="{reddit_url}{encoded_url}" target="_blank">
  <img width="20px" src="https://redditinc.com/hubfs/Reddit%20Inc/Brand/Reddit_Logo.png" alt="Reddit logo">
</a>

<a href="{facebook_url}{encoded_url}" target="_blank">
  <img width="20px" src="https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg" alt="Facebook logo">
</a>
```"""
    return html


# File path from the repository root
file_path = "notebook_template.ipynb"  # @param {type:"string"}

# Include link to Open in BigQuery Studio
INCLUDE_BIGQUERY_STUDIO = False  # @param {type:"boolean"}
display(Markdown(generate_html(file_path)))

| Author(s) |
| --- |
| [Steve Phillips](https://github.com/stevie-p) |

## Overview

This notebook evaluates and compares Gemini models and DocAI custom extractors for an extraction task. 

The task is to accurately extract information from a scanned document with a tabular form.

Within this notebook, we:

* Use the *GenAI Evaluation service* to run the evaluation experiments using multiple models {TODO: and reference forms}
* Use Gemini models with *strucutred output* to ensure well-structured JSON output
* Create a DocAI custom extractor
* Process the DocAI response into a DataFrame
* Run experiments with both Handwritten and Typed forms

The models and custom processors under test are:

* Gemini Models (https://ai.google.dev/gemini-api/docs/models)
    * Gemini 1.5 Pro
    * Gemini 1.5 Flash
    * Gemini 2.0 Flash
    * Gemini 2.5 Flash (Preview)
* DocAI Custom Extractors (https://cloud.google.com/document-ai/docs/processors-list#extract_entities_from_documents)
    * pretrained-foundation-model-v1.2-2024-05-10 (powered by Gemini 1.5 Pro)
    * pretrained-foundation-model-v1.3-2024-08-31 (powered by Gemini 1.5 Flash)
    * pretrained-foundation-model-v1.4-2025-02-05 (powered by Gemini 2.0 Flash)
    * pretrained-foundation-model-v1.5-2025-05-05 (powered by Gemini 2.5 Flash) (NB: US only at time of writing)

## Get started

### Install Google Gen AI SDK and other required packages

In [ ]:
%pip install --upgrade --quiet google-genai jsonschema

### Authenticate your notebook environment (Colab only)

If you're running this notebook on Google Colab, run the cell below to authenticate your environment.

In [ ]:
import sys

if "google.colab" in sys.modules:
    from google.colab import auth

    auth.authenticate_user()

### Set Google Cloud project information

To get started using Vertex AI, you must have an existing Google Cloud project and [enable the Vertex AI API](https://console.cloud.google.com/flows/enableapi?apiid=aiplatform.googleapis.com).

Learn more about [setting up a project and a development environment](https://cloud.google.com/vertex-ai/docs/start/cloud-environment).

In [100]:
# Use the environment variable if the user doesn't provide Project ID.
import os

PROJECT_ID = "docai-436712"  # @param {type: "string", placeholder: "[your-project-id]", isTemplate: true}
if not PROJECT_ID or PROJECT_ID == "[your-project-id]":
    PROJECT_ID = str(os.environ.get("GOOGLE_CLOUD_PROJECT"))

LOCATION = os.environ.get("GOOGLE_CLOUD_REGION", "us-central1")
PROCESSOR_LOCATION = "us"
PROCESSOR_NAME = "eval-extraction-processor"
PROCESSOR_TYPE = "CUSTOM_EXTRACTION_PROCESSOR"

EXPERIMENT_NAME = "eval-gemini-docai"  # @param {type:"string"}
IMAGE_URI = "gs://eval-extraction-examples/IMG_3948.jpeg"
IMAGE_TYPE = "image/jpeg"

import vertexai

vertexai.init(project=PROJECT_ID, location=LOCATION)

### Import libraries

In [94]:
import inspect

import pandas as pd
from vertexai.evaluation import EvalTask, CustomMetric
from vertexai.generative_models import GenerativeModel 
from vertexai.preview.evaluation import notebook_utils
from google import genai
from google.api_core.client_options import ClientOptions
from google.api_core.exceptions import FailedPrecondition
from google.cloud import documentai  # type: ignore
from google.genai.types import (
    FunctionDeclaration,
    GenerateContentConfig,
    GoogleSearch,
    HarmBlockThreshold,
    HarmCategory,
    MediaResolution,
    Part,
    Retrieval,
    SafetySetting,
    Tool,
    ToolCodeExecution,
    VertexAISearch,
)
import json
from jsonschema import validate

## Use Gemini to extract the data

In [5]:
client = genai.Client(vertexai=True, project=PROJECT_ID, location=LOCATION)

# Define which models to compare

models = [
    # Gemini 1.5 family
    "gemini-1.5-pro",
    "gemini-1.5-flash",
    
    # Gemini 2.0 family
    "gemini-2.0-flash",
    
    # Gemini 2.5 family
    "gemini-2.5-flash-preview-05-20"
]

In [9]:
prompt = """
    Analyze the attached scanned form and extract the information in the table in accordance with the schema.
    
    Provide the output in a clean JSON format. 
    
    If a field is blank, illegible, or cannot be found, return null for its value.
    
    If there is no image attached, return null for all fields.
    
"""

# Use structured output to ensure well formatted and consistent JSON output

schema = {
    "type": "object",
    "properties": {
        "rows": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": { "type": "string"},
                    "address": { "type": "string"},
                    "age": {"type": "integer"},
                    "colour": {"type": "string"}
                }
            }
        }
    }
}

generate_content_config = GenerateContentConfig(
    response_mime_type="application/json",
    response_schema=schema,
)

In [102]:
generation_response = []
run_id = notebook_utils.generate_uuid(8)

image = Part.from_uri(file_uri=IMAGE_URI, mime_type=IMAGE_TYPE)
    
for model in models:
    run_name = f"{run_id}-{model}"

    response = client.models.generate_content(
        model=model,
        contents=[
            prompt,
            image
        ],
        config=generate_content_config
    )

    print(f"{run_name}: {response.text}")
    generation_response.append(response.text)

# print(generation_response)

8jc6rfhk-gemini-1.5-pro: {"rows": [{"name": "Joe Bloggs", "address": "123 Main Street", "age": 24, "colour": "Blue"}, {"name": "Jane Doe", "address": "456 Ocean Drive", "age": 31, "colour": "Red"}]}
8jc6rfhk-gemini-1.5-flash: {"rows": [{"name": "Joe Bloggs", "address": "123 Main Street", "age": 24, "colour": "Blue"}, {"name": "Jane Doe", "address": "456 Ocean Drive", "age": 31, "colour": "Red"}]}
8jc6rfhk-gemini-2.0-flash: {
  "rows": [
    {
      "name": "Joe Bloggs",
      "address": "123 Main Street",
      "age": 24,
      "colour": "Blue"
    },
    {
      "name": "Jane Doe",
      "address": "456 Ocean Drive",
      "age": 31,
      "colour": "Red"
    }
  ]
}
8jc6rfhk-gemini-2.5-flash-preview-05-20: {"rows":[{"name":"Joe Bloggs","address":"123 Main Street","age":24,"colour":"Blue"},{"name":"Jane Doe","address":"456 Ocean Drive","age":31,"colour":"Red"}]}

## DocAI

### Create a processor

In [ ]:
opts = ClientOptions(api_endpoint=f"{PROCESSOR_LOCATION}-documentai.googleapis.com")

docai = documentai.DocumentProcessorServiceClient(client_options=opts)

# The full resource name of the location
# e.g.: projects/project_id/locations/location
parent = docai.common_location_path(PROJECT_ID, PROCESSOR_LOCATION)

# Create a processor
processor = docai.create_processor(
    parent=parent,
    processor=documentai.Processor(
        display_name=PROCESSOR_NAME, type_=PROCESSOR_TYPE
    ),
)

In [91]:
# Print the processor information
print(f"Processor Name: {processor.name}")
print(f"Processor Display Name: {processor.display_name}")
print(f"Processor Type: {processor.type_}")

Processor Name: projects/162609893101/locations/us/processors/ba53ef7250ef3794
Processor Display Name: eval-extraction-processor
Processor Type: CUSTOM_EXTRACTION_PROCESSOR

### List processor versions

In [98]:
# Make ListProcessorVersions request
processor_versions = docai.list_processor_versions(parent=processor.name)

# Print the processor version information
for processor_version in processor_versions:
    processor_version_id = docai.parse_processor_version_path(
        processor_version.name
    )["processor_version"]

    print(f"Processor Version: {processor_version_id}")

Processor Version: pretrained-foundation-model-v1.5-2025-05-05
Processor Version: pretrained-foundation-model-v1.4-2025-02-05
Processor Version: pretrained-foundation-model-v1.3-2024-08-31
Processor Version: pretrained-foundation-model-v1.2-2024-05-10
Processor Version: pretrained-foundation-model-v1.1-2024-03-12
Processor Version: pretrained-foundation-model-v1.0-2023-08-22

In [99]:
processor_versions = [
    "pretrained-foundation-model-v1.5-2025-05-05",
    "pretrained-foundation-model-v1.4-2025-02-05",
    "pretrained-foundation-model-v1.3-2024-08-31",
    "pretrained-foundation-model-v1.2-2024-05-10"
]

### Configure the dataset and schema

In [ ]:
# TODO: Configure the dataset and schema

### Create the Process Request

In [111]:
image = documentai.GcsDocument(gcs_uri=IMAGE_URI, mime_type=IMAGE_TYPE)

process_options = documentai.ProcessOptions(    
     schema_override=docai_schema
)

docai_request = documentai.ProcessRequest(gcs_document=image, name=processor.name)
docai_response = docai.process_document(docai_request)

print(docai_response.document)

NameError: name 'docai_schema' is not defined

## Prepare the dataset

In [60]:
prompt = prompt # As above

# image = '{"contents": [{"parts": [{"file_data": {"mime_type": "image/jpeg", "file_uri": "IMAGE_URI"}}]}]}'
    
reference = '{"rows": [{"name": "Joe Bloggs", "address": "123 Main Street", "age": 24, "colour": "Blue"}, {"name": "Jane Doe", "address": "456 Ocean Drive", "age": 31, "colour": "Red"}]}'

response = generation_response

eval_dataset = pd.DataFrame(
    {
        "models": models,
        "prompt": prompt,
        "image": image,
        "reference": reference,
        "response": response
    }
)
eval_dataset

,models,prompt,image,reference,response
0,gemini-1.5-pro,\n Analyze the attached scanned form and ex...,"{""contents"": [{""parts"": [{""file_data"": {""mime_...","{""rows"": [{""name"": ""Joe Bloggs"", ""address"": ""1...","{""rows"": [{""name"": ""Joe Bloggs"", ""address"": ""1..."
1,gemini-1.5-flash,\n Analyze the attached scanned form and ex...,"{""contents"": [{""parts"": [{""file_data"": {""mime_...","{""rows"": [{""name"": ""Joe Bloggs"", ""address"": ""1...","{""rows"": [{""name"": ""Joe Bloggs"", ""address"": ""1..."
2,gemini-2.0-flash,\n Analyze the attached scanned form and ex...,"{""contents"": [{""parts"": [{""file_data"": {""mime_...","{""rows"": [{""name"": ""Joe Bloggs"", ""address"": ""1...","{\n ""rows"": [\n {\n ""name"": ""Joe Blog..."
3,gemini-2.5-flash-preview-05-20,\n Analyze the attached scanned form and ex...,"{""contents"": [{""parts"": [{""file_data"": {""mime_...","{""rows"": [{""name"": ""Joe Bloggs"", ""address"": ""1...","{""rows"":[{""name"":""Joe Bloggs"",""address"":""123 M..."

## Define custom metrics for JSON schema validation

In [61]:
# Check that the reference value is valid according to the schema
validate(instance=json.loads(reference), schema=schema)

In [62]:
def is_valid_schema(instance: dict[str,str]) -> dict[str, float]:
    """Return 1 if the response complies with the schema, 0 if not"""
    
    response = instance["response"]
    
    try:
        validate(instance=json.loads(response), schema=schema)
    except:
        return {
            "valid_schema": 0
        }
    
    return {
        "valid_schema": 1
    }
            
valid_schema = CustomMetric(name="valid_schema", metric_function=is_valid_schema)

In [71]:
def calculate_accuracy(instance: dict[str,str]) -> dict[str, float]:
    """
    This calculates accuracy as equality between the JSON strings by 
    converting to DataFrames and using DataFrame.eq to test of equality elementwise.
    
    Overall accuaracy is calculated between 0 (no elements are equal) and 1.0 (all elements are equal).
    """
    
    ref_rows = json.loads(instance["reference"])["rows"]
    resp_rows = json.loads(instance["response"])["rows"]
    
    # Convert reference and response to DataFrame
    reference_df = pd.DataFrame(ref_rows, index=pd.RangeIndex(len(ref_rows)))
    response_df = pd.DataFrame(resp_rows, index=pd.RangeIndex(len(resp_rows)))
    
    print(f"response: {response_df}")
    
    comparison = reference_df.eq(response_df)
    
    return {
        "accuracy": comparison.mean(axis=1)[0]
    }

accuracy = CustomMetric(name="accuracy", metric_function=calculate_accuracy)

## Define EvalTask & Experiment

In [73]:
extraction_eval_task = EvalTask(
    dataset=eval_dataset,
    metrics=[
        "exact_match",
        valid_schema,
        accuracy
    ],
    experiment=EXPERIMENT_NAME
)

In [74]:
experiment_run_name = f"eval-{run_id}"

eval_result = extraction_eval_task.evaluate(
    # experiment_run_name = experiment_run_name
)

Associating projects/162609893101/locations/us-central1/metadataStores/default/contexts/eval-gemini-docai-27c22265-975d-4564-a978-47d6b42ddd3e to Experiment: eval-gemini-docai

Computing metrics with a total of 12 Vertex Gen AI Evaluation Service API requests.

  0%|          | 0/12 [00:00<?, ?it/s]

reference:          name          address  age colour
0  Joe Bloggs  123 Main Street   24   Blue
1    Jane Doe  456 Ocean Drive   31    Red
response:          name          address  age colour
0  Joe Bloggs  123 Main Street   24   Blue
1    Jane Doe  456 Ocean Drive   31    Red
reference:          name          address  age colour
0  Joe Bloggs  123 Main Street   24   Blue
1    Jane Doe  456 Ocean Drive   31    Red
response:          name          address  age colour
0  Joe Bloggs  123 Main Street   24   Blue
1    Jane Doe  456 Ocean Drive   31    Red
reference:          name          address  age colour
0  Joe Bloggs  123 Main Street   24   Blue
1    Jane Doe  456 Ocean Drive   31    Red
response:          name          address  age colour
0  Joe Bloggs  123 Main Street   24   Blue
1    Jane Doe  456 Ocean Drive   31    Red
reference:          name          address  age colour
0  Joe Bloggs  123 Main Street   24   Blue
1    Jane Doe  456 Ocean Drive   31    Red
response:          name          address  age colour
0  Joe Bloggs  123 Main Street   24   Blue
1    Jane Doe  456 Ocean Drive   31    Red

100%|██████████| 12/12 [00:00<00:00, 32.61it/s]

All 12 metric requests are successfully computed.
Evaluation Took:0.3772368329996425 seconds

In [75]:
notebook_utils.display_eval_result(eval_result=eval_result)

### Summary Metrics

,row_count,exact_match/mean,exact_match/std,valid_schema/mean,valid_schema/std,accuracy/mean,accuracy/std
0,4.0,0.5,0.57735,1.0,0.0,1.0,0.0

### Row-based Metrics

,models,prompt,image,reference,response,valid_schema/score,accuracy/score,exact_match/score
0,gemini-1.5-pro,\n Analyze the attached scanned form and ex...,"{""contents"": [{""parts"": [{""file_data"": {""mime_...","{""rows"": [{""name"": ""Joe Bloggs"", ""address"": ""1...","{""rows"": [{""name"": ""Joe Bloggs"", ""address"": ""1...",1,1.0,1.0
1,gemini-1.5-flash,\n Analyze the attached scanned form and ex...,"{""contents"": [{""parts"": [{""file_data"": {""mime_...","{""rows"": [{""name"": ""Joe Bloggs"", ""address"": ""1...","{""rows"": [{""name"": ""Joe Bloggs"", ""address"": ""1...",1,1.0,1.0
2,gemini-2.0-flash,\n Analyze the attached scanned form and ex...,"{""contents"": [{""parts"": [{""file_data"": {""mime_...","{""rows"": [{""name"": ""Joe Bloggs"", ""address"": ""1...","{\n ""rows"": [\n {\n ""name"": ""Joe Blog...",1,1.0,0.0
3,gemini-2.5-flash-preview-05-20,\n Analyze the attached scanned form and ex...,"{""contents"": [{""parts"": [{""file_data"": {""mime_...","{""rows"": [{""name"": ""Joe Bloggs"", ""address"": ""1...","{""rows"":[{""name"":""Joe Bloggs"",""address"":""123 M...",1,1.0,0.0

## Cleaning up

{TODO: Clean up resources created in this notebook. If no resources are created in this notebook, remove this section}

Delete Processor

Delete Experiment(s)